### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by flakerimi** [altinukshini/prishtinabuses#1]
Meqe shume pak css kishit, bejeni embed ne html. Ske nevoje me bo request per kaq css.

**Comment by altinukshini** [comment]
U kry, flm :)
Btw duhet me kqyre CSS-in npergjithesi edhe ne Openlayers../themes/default/ se ne browsera te ndryshem pi qet do sene ndryshe... une kom punu veq ne Firefox.
thnx.

**Comment by flakerimi** [comment]
Mire eshte me perdor CSS Reset, qe me i resetu browserat krejt njejt. Google it, edhe e bon paste on top of first loaded css file. :).
